services:
  - type: web
    name: checklist-qualidade-suporte-b2b
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_ZENDESK_SUBDOMAIN
        sync: false
      - key: VITE_ZENDESK_EMAIL
        sync: false
      - key: VITE_ZENDESK_API_TOKEN
        sync: false
      - key: VITE_WEBHOOK_URL
        sync: false